### ISSUE TITLE
Obsidian plugin

### ISSUE THREAD

**Issue by javiavid** [hotoo/markline#19]
I think markline would integrate very well with obsidian.
Have you thought about making a plugin?

**Comment by hotoo** [comment]
Good idea, let me see how to make a obsidian plugin.

**Comment by javiavid** [comment]
Thanks

**Comment by hotoo** [comment]
@javiavid https://github.com/hotoo/obsidian-markline

**Comment by javiavid** [comment]
I just tried it and it works great. Thank you so much!
